app/Http/routes.php
<?php
/**
 * Contains the route definitions.
 *
 * This file calls the various functions on the Route to register all routes
 * and resources defined by the application.
 *
 * PHP Version 5
 *
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

// Application root
Route::get('/', ['as' => 'root', 'uses' => 'RootController@root']);

// Authentication & Registration
Route::get('auth/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister']);

Route::get('person/autocomplete', ['as' => 'person.autocomplete', 'uses' => 'PersonController@autocomplete']);
Route::resource('person', 'PersonController');
Route::resource('person.award', 'QualificationAwardController');
Route::resource('project_role', 'ProjectRoleController');
Route::resource('qualification', 'QualificationController');
Route::resource('funder', 'FunderController');
Route::get(
    'funding_app/autocomplete',
    ['as' => 'funding_app.autocomplete',
    'uses' => 'FundingApplicationController@autocomplete']
);
Route::resource('funding_app', 'FundingApplicationController');
Route::resource('funding_app.applicant', 'FundingApplicantController');
Route::resource('project', 'ProjectController');
Route::resource('project.participant', 'ProjectParticipantController');
Route::resource('project.funding', 'ProjectFundingController');

app/Models/Project.php
<?php
/**
 * Contains the Project model.
 *
 * PHP Version 5
 *
 * @package ADoc\Http\Models
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

namespace ADoc\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * The Project model represents a project.
 *
 * It contains the following fields:
 *
 * * user_id - The id of the User who owns this Project
 * * title - Title of this Project
 * * acronym - Acronym of this Project (optional)
 * * summary - A longer textual summary of the Project
 * * start - The start date for this Project
 * * end - The end date for this Project
 * * stage - The current stage of the Project (planning/active/inactive/complete)
 * * status - Status public or private to restrict access
 */
class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
            'title',
            'acronym',
            'summary',
            'start',
            'end',
            'stage',
            'status'
    ];

    /**
     * Returns all ProjectParticipants that are linked to this Project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function participants()
    {
        return $this->hasMany('ADoc\Models\ProjectParticipant');
    }
    
    /**
     * Returns all ProjectFundings that are linked to this Project.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function fundings()
    {
        return $this->hasMany('ADoc\Models\ProjectFunding');
    }
}

app/Http/Controllers/ProjectController.php
<?php
/**
 * Controller for the Project.
 *
 * PHP Version 5
 *
 * @package ADoc\Http\Controllers
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

namespace ADoc\Http\Controllers;

use Auth;
use Illuminate\Http\Request;

use ADoc\Http\Requests\ProjectRequest;
use ADoc\Http\Controllers\Controller;
use ADoc\Models\Project;

/**
 * The ProjectController provides the functionality for listing, showing, creating,
 * updating and deleting Projects.
 */
class ProjectController extends Controller
{
    /**
     * Display a paginatable listing of Projects.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     *
     * @return Response The "project/index" view
     */
    public function index(ProjectRequest $request)
    {
        if (Auth::check() && Auth::user()->can('projects.view')) {
            $projects = Project::orderBy('end', 'desc')->orderBy('start', 'desc')
                ->orderBy('title', 'asc')->paginate(10);
        } elseif (Auth::check()) {
            $projects = Project::where('status', 'public')->orWhere('user_id', Auth::user()->id)
                ->orderBy('end', 'desc')->orderBy('start', 'desc')->orderBy('title', 'asc')->paginate(10);
        } else {
            $projects = Project::where('status', 'public')
                ->orderBy('end', 'desc')->orderBy('start', 'desc')->orderBy('title', 'asc')->paginate(10);
        }
        return view('project/index', ['projects' => $projects]);
    }

    /**
     * Show the form for creating a new Project.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     *
     * @return Response The "project/create" view.
     */
    public function create(ProjectRequest $request)
    {
        return view('project/create');
    }

    /**
     * Store a newly created Project in storage.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     *
     * @return Response Redirect to "project.show" if successful or "project.create" otherwise
     */
    public function store(ProjectRequest $request)
    {
        $project = new Project();
        $project->fill($request->all());
        $project->user_id = Auth::user()->id;
        if ($request->get('acronym') === '') {
            $project->acronym = null;
        }
        if ($request->get('start') === '') {
            $project->start = null;
        }
        if ($request->get('end') === '') {
            $project->end = null;
        }
        $project->save();
        return redirect()->route('project.show', $project);
    }

    /**
     * Display the specified Project.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     * @param int            $id      The unique identifier of the Project to show
     *
     * @return Response The "project/show" view
     */
    public function show(ProjectRequest $request, $id)
    {
        $project = Project::findOrFail($id);
        return view('project/show', ['project' => $project]);
    }

    /**
     * Show the form for editing the specified Project.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     * @param int            $id      The unique identifier of the Project to edit
     *
     * @return Response The "project/edit" view
     */
    public function edit(ProjectRequest $request, $id)
    {
        $project = Project::findOrFail($id);
        return view('project/edit', ['project' => $project]);
    }

    /**
     * Update the specified Project in storage.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     * @param int            $id      The unique identifier of the Project to update
     *
     * @return Response Redirect to "project.show" if successful or "project.edit" otherwise
     */
    public function update(ProjectRequest $request, $id)
    {
        $project = Project::findOrFail($id);
        $project->fill($request->all());
        if ($request->get('acronym') === '') {
            $project->acronym = null;
        }
        if ($request->get('start') === '') {
            $project->start = null;
        }
        if ($request->get('end') === '') {
            $project->end = null;
        }
        $project->save();
        return redirect()->route('project.show', $project);
    }

    /**
     * Remove the specified Project from storage.
     *
     * @param ProjectRequest $request The request to use for validation and authentication
     * @param int            $id      The unique identifier of the Project to remove
     *
     * @return Response Redirect to "project.index"
     */
    public function destroy(ProjectRequest $request, $id)
    {
        $project = Project::findOrFail($id);
        $project->participants()->delete();
        $project->delete();
        return redirect()->route('project.index');
    }
}

resources/views/project/create.blade.php
@extends('../layout')
@section('title', 'Add a new Project')
@section('breadcrumbs')
  <li><a href="{{route('project.index')}}">Projects</a></li>
  <li class="current"><a href="{{route('project.create')}}">Add</a></li>
  @endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Add a new Project</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::open(['route' => 'project.store']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'title', 'label' => 'Title'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'acronym', 'label' => 'Acronym'])
        @include('../partials/_form_field', ['field_type' => 'textarea', 'field_name' => 'summary', 'label' => 'Summary'])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'start', 'label' => 'Start Date'])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'end', 'label' => 'End Date'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'stage', 'label' => 'Stage', 'values' => ['planning' => 'Planning', 'active' => 'Active', 'inactive' => 'Inactive', 'completed' => 'Completed']])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'status', 'label' => 'Status', 'values' => ['private' => 'Private', 'public' => 'Public']])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Add"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/project/edit.blade.php
@extends('../layout')
@section('title', $project->title . ' - Edit')
@section('breadcrumbs')
  <li><a href="{{route('project.index')}}">Projects</a></li>
  <li><a href="{{route('project.show', [$project])}}">{{$project->title}}</a>
  <li class="current"><a href="{{route('project.edit', [$project])}}">Edit</a>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>{{$project->title}} - Edit</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::model($project, ['route' => ['project.update', $project], 'method' => 'PUT']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'title', 'label' => 'Title'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'acronym', 'label' => 'Acronym'])
        @include('../partials/_form_field', ['field_type' => 'textarea', 'field_name' => 'summary', 'label' => 'Summary'])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'start', 'label' => 'Start Date'])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'end', 'label' => 'End Date'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'stage', 'label' => 'Stage', 'values' => ['planning' => 'Planning', 'active' => 'Active', 'inactive' => 'Inactive', 'completed' => 'Completed']])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'status', 'label' => 'Status', 'values' => ['private' => 'Private', 'public' => 'Public']])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Update"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/project/index.blade.php
@extends('../layout')
@section('title', 'Projects')
@section('breadcrumbs')
  <li class="current"><a href="{{route('project.index')}}">Projects</a></li>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Projects</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12">
      <table class="small-12">
        <thead>
          <tr>
            <th>Title</th>
            <th>Start</th>
            <th>End</th>
            <th>Stage</th>
          </tr>
        </thead>
        <tbody>
          @foreach($projects as $project)
            <tr>
              <td><a href="{{route('project.show', [$project])}}">{{$project->title}}</a></td>
              <td>{{$project->start}}</td>
              <td>{{$project->end}}</td>
              <td>
                @if($project->stage === 'planning')
                  Planning
                @elseif($project->stage === 'active')
                  Active
                @elseif($project->stage === 'inactive')
                  Inactive
                @elseif($project->stage === 'completed')
                  Completed
                @endif
              </td>
            </tr>
          @endforeach
          @if(count($projects) == 0)
            <tr>
              <td colspan="4" class="nothing-found">No projects were found</td>
            </tr>
          @endif
        </tbody>
      </table>
      {!! (new ADoc\Helpers\Pagination($projects))->render() !!}
    </div>
  </div>
@endsection

resources/views/project/show.blade.php
@extends('../layout')
@section('title', $project->title)
@section('breadcrumbs')
  <li><a href="{{route('project.index')}}">Projects</a></li>
  <li class="current"><a href="{{route('project.show', [$project])}}">{{$project->title}}</a>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      @if(Auth::check())
        <div class="right">
          @allowed('project.edit', $project)
            <a href="{{route('project.edit', [$project])}}" class="button tiny">Edit</a>
          @endallowed
          @allowed('project.delete', $project)
            <a href="{{route('project.destroy', [$project])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmDeleteSettings('project', $project->title)}}" data-token="{{csrf_token()}}">Delete</a>
          @endallowed
        </div>
      @endif
      <h1>{{$project->title}}
        @if($project->acronym)
          ({{$project->acronym}})
        @endif
        <small>{{$project->stage}}</small>
      </h1>
      <dl>
        @if($project->start)
          <dt class="column small-6 medium-4 large-3">Start Date</dt>
          <dd class="column small-6 medium-8 large-9">{{$project->start}}</dd>
        @endif
        @if($project->end)
          <dt class="column small-6 medium-4 large-3">End Date</dt>
          <dd class="column small-6 medium-8 large-9">{{$project->end}}</dd>
        @endif
      </dl>
      <h2>Summary</h2>
      <p>{{$project->summary}}</p>
      @if(count($project->participants()->getResults()) > 0 || (Auth::check() && Auth::user()->allowed('project.edit', $project)))
        <h2>People</h2>
        <table>
          <thead>
            <tr>
              <th>Role</th>
              <th>Name</th>
              <th>Allocation</th>
              @allowed('project.edit', $project)
                <th>Action</th>
              @endallowed
            </tr>
          </thead>
          <tbody>
            @foreach($project->participants()->getResults() as $participant)
              <tr>
                <td><abbr title="{{$participant->role()->long}}">{{$participant->role()->short}}</abbr></td>
                <td>
                  @if($participant->person()->status == 'public' || (Auth::check() && Auth::user()->allowed('person.view', $participant->person())))
                    <a href="{{route('person.show', [$participant->person()])}}">{{$participant->person()->fullName()}}</a>
                  @else
                    {{$participant->person()->fullName()}}
                  @endif
                </td>
                <td>{{$participant->allocation}}</td>
                @allowed('project.edit', $project)
                  <td>
                    <a href="{{route('project.participant.edit', [$project, $participant])}}" class="button tiny">Edit</a>
                    <a href="{{route('project.participant.destroy', [$project, $participant])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmActionSettings('remove', 'person', $participant->person()->fullName())}}" data-token="{{csrf_token()}}">Remove</a>
                  </td>
                @endif
              </tr>
            @endforeach
            @if(count($project->participants()->getResults()) === 0)
              <tr>
                <td colspan="4" class="nothing-found">No people linked to this project</td>
              </tr>
            @endif
          </tbody>
        </table>
        @allowed('project.edit', $project)
          <a href="{{route('project.participant.create', [$project])}}" class="button tiny">Add</a>
        @endallowed
      @endif
      @if(count($project->fundings()->getResults()) > 0 || (Auth::check() && Auth::user()->allowed('project.edit', $project)))
        <h2>Funding</h2>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Amount</th>
              @allowed('project.edit', $project)
                <th>Action</th>
              @endallowed
            </tr>
          </thead>
          <tbody>
            @foreach($project->fundings()->getResults() as $funding)
              <tr>
                <td>
                  @if($funding->fundingApplication()->status == 'public' || (Auth::check() && Auth::user()->allowed('fundingapplication.view', $funding->fundingApplication())))
                    <a href="{{route('funding_app.show', [$funding->fundingApplication()])}}">{{$funding->fundingApplication()->title}}</a>
                  @else
                    {{$funding->fundingApplication()->title}}
                  @endif
                </td>
                <td>{{strtoupper($funding->currency)}} {{number_format($funding->amount, 2)}}</td>
                @allowed('project.edit', $project)
                  <td>
                    <a href="{{route('project.funding.edit', [$project, $funding])}}" class="button tiny">Edit</a>
                    <a href="{{route('project.funding.destroy', [$project, $funding])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmActionSettings('remove', 'funding', $funding->fundingApplication()->title)}}" data-token="{{csrf_token()}}">Remove</a>
                  </td>
                @endif
              </tr>
            @endforeach
            @if(count($project->fundings()->getResults()) === 0)
              <tr>
                <td colspan="4" class="nothing-found">No funding linked to this project</td>
              </tr>
            @endif
          </tbody>
        </table>
        @allowed('project.edit', $project)
          <a href="{{route('project.funding.create', [$project])}}" class="button tiny">Add</a>
        @endallowed
      @endif
    </div>
  </div>
@endsection
@section('javascript')
  <script>
  $('a[data-method]').postLink();
  </script>
@endsection