app/Http/routes.php
<?php
/**
 * Contains the route definitions.
 *
 * This file calls the various functions on the Route to register all routes
 * and resources defined by the application.
 *
 * PHP Version 5
 *
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

// Application root
Route::get('/', ['as' => 'root', 'uses' => 'RootController@root']);

// Authentication & Registration
Route::get('auth/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister']);

Route::get('person/autocomplete', ['as' => 'person.autocomplete', 'uses' => 'PersonController@autocomplete']);
Route::resource('person', 'PersonController');
Route::resource('person.award', 'QualificationAwardController');
Route::resource('project_role', 'ProjectRoleController');
Route::resource('qualification', 'QualificationController');
Route::resource('funder', 'FunderController');
Route::get(
    'funding_app/autocomplete',
    ['as' => 'funding_app.autocomplete',
    'uses' => 'FundingApplicationController@autocomplete']
);
Route::resource('funding_app', 'FundingApplicationController');
Route::resource('funding_app.applicant', 'FundingApplicantController');
Route::resource('project', 'ProjectController');
Route::resource('project.participant', 'ProjectParticipantController');
Route::resource('project.funding', 'ProjectFundingController');

resources/views/funding_app/create.blade.php
@extends('../layout')
@section('title', 'Add a new Funding Application')
@section('breadcrumbs')
  <li><a href="{{route('funding_app.index')}}">Funding Applications</a></li>
  <li class="current"><a href="{{route('funding_app.create')}}">Add</a></li>
  @endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Add a new Funding Application</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::open(['route' => 'funding_app.store']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'title', 'label' => 'Title'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'funder_id', 'label' => 'Funder', 'values' => $funders])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'scheme', 'label' => 'Scheme'])
        @include('../partials/_form_field', ['field_type' => 'number', 'field_name' => 'amount', 'label' => 'Amount'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'currency', 'label' => 'Currency', 'values' => ['eur' => 'Euros', 'gbp' => 'British Pound']])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'submission_date', 'label' => 'Submission Date'])
        @include('../partials/_form_field', ['field_type' => 'textarea', 'field_name' => 'summary', 'label' => 'Summary'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'stage', 'label' => 'Stage', 'values' => ['preparation' => 'In Preparation', 'review' => 'Under Review', 'decision' => 'Decision received']])
        @include('../partials/_form_field', ['field_type' => 'checkbox', 'field_name' => 'success', 'label' => 'Successful'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'status', 'label' => 'Status', 'values' => ['private' => 'Private', 'public' => 'Public']])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Add"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/funding_app/edit.blade.php
@extends('../layout')
@section('title', $funding_app->title . ' - Edit')
@section('breadcrumbs')
  <li><a href="{{route('funding_app.index')}}">Funding Applications</a></li>
  <li><a href="{{route('funding_app.show', [$funding_app])}}">{{$funding_app->title}}</a>
  <li class="current"><a href="{{route('funding_app.edit', [$funding_app])}}">Edit</a>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>{{$funding_app->title}} - Edit</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::model($funding_app, ['route' => ['funding_app.update', $funding_app], 'method' => 'PUT']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'title', 'label' => 'Title'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'funder_id', 'label' => 'Funder', 'values' => $funders])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'scheme', 'label' => 'Scheme'])
        @include('../partials/_form_field', ['field_type' => 'number', 'field_name' => 'amount', 'label' => 'Amount'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'currency', 'label' => 'Currency', 'values' => ['eur' => 'Euros', 'gbp' => 'British Pound']])
        @include('../partials/_form_field', ['field_type' => 'date', 'field_name' => 'submission_date', 'label' => 'Submission Date'])
        @include('../partials/_form_field', ['field_type' => 'textarea', 'field_name' => 'summary', 'label' => 'Summary'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'stage', 'label' => 'Stage', 'values' => ['preparation' => 'In Preparation', 'review' => 'Under Review', 'decision' => 'Decision received']])
        @include('../partials/_form_field', ['field_type' => 'checkbox', 'field_name' => 'success', 'label' => 'Successful'])
        @include('../partials/_form_field', ['field_type' => 'select', 'field_name' => 'status', 'label' => 'Status', 'values' => ['private' => 'Private', 'public' => 'Public']])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Update"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/funding_app/index.blade.php
@extends('../layout')
@section('title', 'Funding Applications')
@section('breadcrumbs')
  <li class="current"><a href="{{route('funding_app.index')}}">Funding Applications</a></li>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Funding Applications</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12">
      <table class="small-12">
        <thead>
          <tr>
            <th>Title</th>
            <th>Funder</th>
            <th>Amount</th>
            <th>Stage</th>
            @if(Auth::check())
              <th>Successful</th>
            @endif
          </tr>
        </thead>
        <tbody>
          @foreach($funding_apps as $funding_app)
            <tr>
              <td><a href="{{route('funding_app.show', [$funding_app])}}">{{$funding_app->title}}</a></td>
              <td><a href="{{route('funder.show', [$funding_app->funder()])}}"><abbr title="{{$funding_app->funder()->name}} - {{$funding_app->funder()->country}}">{{$funding_app->funder()->abbreviation}}</abbr></a></td>
              <td>
                @if($funding_app->amount)
                  {{strtoupper($funding_app->currency)}} {{number_format($funding_app->amount, 2)}}
                @endif
              </td>
              <td>
                @if($funding_app->stage === 'preparation')
                  In preparation
                @elseif($funding_app->stage === 'review')
                  Under review
                @elseif($funding_app->stage === 'decision')
                  Decision received
                @endif
              </td>
              <td>@if($funding_app->stage === 'decision')
                  {{$funding_app->success ? 'Yes' : 'No'}}
                @endif
              </td>
            </tr>
          @endforeach
          @if(count($funding_apps) == 0)
            <tr>
              <td colspan="4" class="nothing-found">No funding applications were found</td>
            </tr>
          @endif
        </tbody>
      </table>
      {!! (new ADoc\Helpers\Pagination($funding_apps))->render() !!}
    </div>
  </div>
@endsection

resources/views/funding_app/show.blade.php
@extends('../layout')
@section('title', $funding_app->title)
@section('breadcrumbs')
  <li><a href="{{route('funding_app.index')}}">Funding Applications</a></li>
  <li class="current"><a href="{{route('funding_app.show', [$funding_app])}}">{{$funding_app->title}}</a>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      @if(Auth::check())
        <div class="right">
          @allowed('fundingapplication.edit', $funding_app)
            <a href="{{route('funding_app.edit', [$funding_app])}}" class="button tiny">Edit</a>
          @endallowed
          @allowed('fundingapplication.delete', $funding_app)
            <a href="{{route('funding_app.destroy', [$funding_app])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmDeleteSettings('funding application', $funding_app->title)}}" data-token="{{csrf_token()}}">Delete</a>
          @endallowed
        </div>
      @endif
      <h1>{{$funding_app->title}}
        <small>
          @if($funding_app->stage === 'preparation')
            in preparation
          @elseif($funding_app->stage === 'review')
            under review
          @elseif($funding_app->stage === 'decision' && $funding_app->success)
            successful
          @elseif($funding_app->stage === 'decision' && !$funding_app->success)
            unsuccessful
          @endif
        </small>
      </h1>
      <dl>
        <dt class="column small-6 medium-4 large-3">Funder</dt>
        <dd class="column small-6 medium-8 large-9"><a href="{{route('funder.show', $funding_app->funder())}}">{{$funding_app->funder()->name}}</a> ({{$funding_app->funder()->country}})</dd>
        @if($funding_app->scheme !== '')
          <dt class="column small-6 medium-4 large-3">Scheme</dt>
          <dd class="column small-6 medium-8 large-9">{{$funding_app->scheme}}</dd>
        @endif
        @if($funding_app->amount)
          <dt class="column small-6 medium-4 large-3">Amount</dt>
          <dd class="column small-6 medium-8 large-9">{{strtoupper($funding_app->currency)}} {{number_format($funding_app->amount, 2)}}</dd>
        @endif
        @if($funding_app->submission_date)
          <dt class="column small-6 medium-4 large-3">Submitted</dt>
          <dd class="column small-6 medium-8 large-9">{{$funding_app->submission_date}}</dd>
        @endif
      </dl>
      <h2>Summary</h2>
      <p>{{$funding_app->summary}}</p>
      @if(count($funding_app->applicants()->getResults()) > 0 || (Auth::check() && Auth::user()->allowed('fundingapplication.edit', $funding_app)))
        <h2>People</h2>
        <table>
          <thead>
            <tr>
              <th>Role</th>
              <th>Name</th>
              <th>Allocation</th>
              @allowed('fundingapplication.edit', $funding_app)
                <th>Action</th>
              @endallowed
            </tr>
          </thead>
          <tbody>
            @foreach($funding_app->applicants()->getResults() as $applicant)
              <tr>
                <td><abbr title="{{$applicant->role()->long}}">{{$applicant->role()->short}}</abbr></td>
                <td>
                  @if($applicant->person()->status == 'public' || (Auth::check() && Auth::user()->can('person.view', $applicant->person())))
                    <a href="{{route('person.show', [$applicant->person()])}}">{{$applicant->person()->fullName()}}</a>
                  @else
                    {{$applicant->person()->fullName()}}
                  @endif
                </td>
                <td>{{$applicant->allocation}}</td>
                @allowed('fundingapplication.edit', $funding_app)
                  <td>
                    <a href="{{route('funding_app.applicant.edit', [$funding_app, $applicant])}}" class="button tiny">Edit</a>
                    <a href="{{route('funding_app.applicant.destroy', [$funding_app, $applicant])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmActionSettings('remove', 'person', $applicant->person()->fullName())}}" data-token="{{csrf_token()}}">Remove</a>
                  </td>
                @endif
              </tr>
            @endforeach
            @if(count($funding_app->applicants()->getResults()) === 0)
              <tr>
                <td colspan="4" class="nothing-found">No people linked to this funding application</td>
              </tr>
            @endif
          </tbody>
        </table>
        @allowed('fundingapplication.edit', $funding_app)
          <a href="{{route('funding_app.applicant.create', $funding_app->id)}}" class="button tiny">Add</a>
        @endallowed
      @endif
      @if(count($funding_app->fundings()->getResults()) > 0 || (Auth::check() && Auth::user()->allowed('fundingapplication.edit', $funding_app)))
        <h2>Funded Projects</h2>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            @foreach($funding_app->fundings()->getResults() as $funding)
              <tr>
                <td>
                  @if($funding->project()->status == 'public' || (Auth::check() && Auth::user()->allowed('project.view', $funding->project())))
                    <a href="{{route('project.show', [$funding->project()])}}">{{$funding->project()->title}}</a>
                  @else
                    {{$funding->project()->title}}
                  @endif
                </td>
                <td>{{strtoupper($funding->currency)}} {{number_format($funding->amount, 2)}}</td>
              </tr>
            @endforeach
            @if(count($funding_app->fundings()->getResults()) === 0)
              <tr>
                <td colspan="2" class="nothing-found">No projects linked to this funding application</td>
              </tr>
            @endif
          </tbody>
        </table>
      @endif
    </div>
  </div>
@endsection
@section('javascript')
  <script>
  $('a[data-method]').postLink();
  </script>
@endsection