app/Http/routes.php
<?php
/**
 * Contains the route definitions.
 *
 * This file calls the various functions on the Route to register all routes
 * and resources defined by the application.
 *
 * PHP Version 5
 *
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

// Application root
Route::get('/', ['as' => 'root', 'uses' => 'RootController@root']);

// Authentication & Registration
Route::get('auth/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', ['uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register', ['uses' => 'Auth\AuthController@postRegister']);

Route::get('person/autocomplete', ['as' => 'person.autocomplete', 'uses' => 'PersonController@autocomplete']);
Route::resource('person', 'PersonController');
Route::resource('person.award', 'QualificationAwardController');
Route::resource('project_role', 'ProjectRoleController');
Route::resource('qualification', 'QualificationController');
Route::resource('funder', 'FunderController');
Route::get(
    'funding_app/autocomplete',
    ['as' => 'funding_app.autocomplete',
    'uses' => 'FundingApplicationController@autocomplete']
);
Route::resource('funding_app', 'FundingApplicationController');
Route::resource('funding_app.applicant', 'FundingApplicantController');
Route::resource('project', 'ProjectController');
Route::resource('project.participant', 'ProjectParticipantController');
Route::resource('project.funding', 'ProjectFundingController');

app/Models/Funder.php
<?php
/**
 * Contains the Funder model.
 *
 * PHP Version 5
 *
 * @package ADoc\Http\Models
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

namespace ADoc\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * The Funder model represents a funding body.
 *
 * It contains the following fields:
 *
 * * name - The name of the funding boddy
 * * abbreviation - Abbreviated name of the funding body
 * * country - The country the funding body is based in
 */
class Funder extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'abbreviation', 'country'];
}

app/Http/Controllers/FunderController.php
<?php
/**
 * Controller for the Funder.
 *
 * PHP Version 5
 *
 * @package ADoc\Http\Controllers
 * @author  Mark Hall <Mark.Hall@edgehill.ac.uk>
 * @license https://gnu.org/licenses/agpl.html GNU Affero General Public License
 */

namespace ADoc\Http\Controllers;

use Illuminate\Http\Request;

use ADoc\Http\Requests\FunderRequest;
use ADoc\Http\Controllers\Controller;
use ADoc\Models\Funder;

/**
 * The FunderController provides the functionality for listing, showing, creating,
 * updating and deleting Funders.
 *
 * @package ADoc\Http\Controllers
 */
class FunderController extends Controller
{
    /**
     * Display a paginatable listing of Funders.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     *
     * @return Response The "funder/index" view.
     */
    public function index(FunderRequest $request)
    {
        $funders = Funder::orderby('name', 'asc')->paginate(30);
        return view('funder/index', ['funders' => $funders]);
    }

    /**
     * Show the form for creating a new Funder.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     *
     * @return Response The "funder/create" view.
     */
    public function create(FunderRequest $request)
    {
        return view('funder/create');
    }

    /**
     * Store a newly created Funder in storage.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     *
     * @return Response Redirect to "funder.show" if successful and "funder.create" if not
     */
    public function store(FunderRequest $request)
    {
        $funder = new Funder();
        $funder->fill($request->all());
        $funder->save();
        return redirect()->route('funder.show', $funder);
    }

    /**
     * Display the specified Funder.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     * @param int           $id      The unique identifier of the Funder to show
     *
     * @return Response The "funder/show" view.
     */
    public function show(FunderRequest $request, $id)
    {
        $funder = Funder::findOrFail($id);
        return view('funder/show', ['funder' => $funder]);
    }

    /**
     * Show the form for editing the specified Funder.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     * @param int           $id      The unique identifier of the Funder to edit
     *
     * @return Response The "funder/edit" view.
     */
    public function edit(FunderRequest $request, $id)
    {
        $funder = Funder::findOrFail($id);
        return view('funder/edit', ['funder' => $funder]);
    }

    /**
     * Update the specified Funder in storage.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     * @param int           $id      The unique identifier of the Funder to update
     *
     * @return Response Redirect to "funder.show" if successful or "funder.edit" otherwise.
     */
    public function update(FunderRequest $request, $id)
    {
        $funder = Funder::findOrFail($id);
        $funder->fill($request->all());
        $funder->save();
        return redirect()->route('funder.show', $funder);
    }

    /**
     * Remove the specified Funder from storage.
     *
     * @param FunderRequest $request The request to use for validation and authentication
     * @param int           $id      The unique identifier of the Funder to remove
     *
     * @return Response Redirect to "funder.index".
     */
    public function destroy(FunderRequest $request, $id)
    {
        $funder = Funder::findOrFail($id);
        $funder->delete();
        return redirect()->route('funder.index');
    }
}

resources/views/funder/create.blade.php
@extends('../layout')
@section('title', 'Add a new Funder')
@section('breadcrumbs')
  <li><a href="{{route('funder.index')}}">Funders</a></li>
  <li class="current"><a href="{{route('funder.create')}}">Add</a></li>
  @endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Add a new Funder</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::open(['route' => 'funder.store']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'name', 'label' => 'Name'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'abbreviation', 'label' => 'Abbreviation'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'country', 'label' => 'Country'])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Add"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/funder/edit.blade.php
@extends('../layout')
@section('title', $funder->name . ' - Edit')
@section('breadcrumbs')
  <li><a href="{{route('person.index')}}">Funders</a></li>
  <li><a href="{{route('funder.show', [$funder])}}">{{$funder->abbreviation}}</a>
  <li class="current"><a href="{{route('funder.edit', [$funder])}}">Edit</a>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>{{$funder->abbreviation}} - Edit</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12 medium-8 large-6">
      {!! Form::model($funder, ['route' => ['funder.update', $funder], 'method' => 'PUT']) !!}
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'name', 'label' => 'Name'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'abbreviation', 'label' => 'Abbreviation'])
        @include('../partials/_form_field', ['field_type' => 'text', 'field_name' => 'country', 'label' => 'Country'])
        <div class="row collapse">
          <div class="column small-12 text-right">
            <input type="submit" class="button" value="Update"/>
          </div>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
  @endsection

resources/views/funder/index.blade.php
@extends('../layout')
@section('title', 'Funders')
@section('breadcrumbs')
  <li class="current"><a href="{{route('funder.index')}}">Funders</a></li>
@endsection
@section('content')
  <div class="row">
    <div class="column small-12">
      <h1>Funders</h1>
    </div>
  </div>
  <div class="row">
    <div class="column small-12">
      <table class="small-12">
        <thead>
          <tr>
            <th>Name</th>
            <th>Abbreviation</th>
            <th>Country</th>
          </tr>
        </thead>
        <tbody>
          @foreach($funders as $funder)
            <tr>
              <td><a href="{{route('funder.show', [$funder])}}">{{$funder->name}}</a></td>
              <td>{{$funder->abbreviation}}</td>
              <td>{{$funder->country}}</td>
            </tr>
          @endforeach
          @if(count($funders) == 0)
            <tr>
              <td colspan="4" class="nothing-found">No funders were found</td>
            </tr>
          @endif
        </tbody>
      </table>
      {!! (new ADoc\Helpers\Pagination($funders))->render() !!}
    </div>
  </div>
@endsection

resources/views/funder/show.blade.php
@extends('../layout')
@section('title', $funder->name)
@section('breadcrumbs')
    <li><a href="{{route('funder.index')}}">Funders</a></li>
    <li class="current"><a href="{{route('funder.show', [$funder])}}">{{$funder->abbreviation}}</a>
        @endsection
        @section('content')
            <div class="row">
                <div class="column small-12">
                    @if(Auth::check())
                        <div class="right">
                            @permission('funder.edit')
                            <a href="{{route('funder.edit', [$funder])}}" class="button tiny">Edit</a>
                            @endpermission
                            @permission('funder.delete')
                            <a href="{{route('funder.destroy', [$funder])}}" class="button tiny alert" data-method="DELETE" data-confirm="{{UI::confirmDeleteSettings('funder', $funder->name)}}" data-token="{{csrf_token()}}">Delete</a>
                            @endpermission
                        </div>
                    @endif
                    <h1>{{$funder->name}} <small>({{$funder->abbreviation}})</small></h1>
                    <p>{{$funder->country}}</p>
                    </table>
                </div>
            </div>
        @endsection
        @section('javascript')
            <script>
                $('a[data-method]').postLink();
            </script>
@endsection